spring.application.name=test
app.pdfmerge.path=/home/prashant/Downloads/Project/test/PdfMerger

spring.datasource.url=jdbc:postgresql://localhost:5432/filemerger
spring.datasource.username=prashant
spring.datasource.password=pass@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


